/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MovieRouteImport } from './routes/movie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as MovieIndexRouteImport } from './routes/movie/index'
import { Route as TvTopRatedRouteImport } from './routes/tv/top-rated'
import { Route as TvOnTheAirRouteImport } from './routes/tv/on-the-air'
import { Route as TvAiringTodayRouteImport } from './routes/tv/airing-today'
import { Route as TvIdRouteImport } from './routes/tv/$id'
import { Route as MovieUpcomingRouteImport } from './routes/movie/upcoming'
import { Route as MovieTopRatedRouteImport } from './routes/movie/top-rated'
import { Route as MovieNowPlayingRouteImport } from './routes/movie/now-playing'
import { Route as MovieIdRouteImport } from './routes/movie/$id'

const MovieRoute = MovieRouteImport.update({
  id: '/movie',
  path: '/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIndexRoute = MovieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MovieRoute,
} as any)
const TvTopRatedRoute = TvTopRatedRouteImport.update({
  id: '/tv/top-rated',
  path: '/tv/top-rated',
  getParentRoute: () => rootRouteImport,
} as any)
const TvOnTheAirRoute = TvOnTheAirRouteImport.update({
  id: '/tv/on-the-air',
  path: '/tv/on-the-air',
  getParentRoute: () => rootRouteImport,
} as any)
const TvAiringTodayRoute = TvAiringTodayRouteImport.update({
  id: '/tv/airing-today',
  path: '/tv/airing-today',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdRoute = TvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieUpcomingRoute = MovieUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => MovieRoute,
} as any)
const MovieTopRatedRoute = MovieTopRatedRouteImport.update({
  id: '/top-rated',
  path: '/top-rated',
  getParentRoute: () => MovieRoute,
} as any)
const MovieNowPlayingRoute = MovieNowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => MovieRoute,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MovieRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie': typeof MovieRouteWithChildren
  '/movie/$id': typeof MovieIdRoute
  '/movie/now-playing': typeof MovieNowPlayingRoute
  '/movie/top-rated': typeof MovieTopRatedRoute
  '/movie/upcoming': typeof MovieUpcomingRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/airing-today': typeof TvAiringTodayRoute
  '/tv/on-the-air': typeof TvOnTheAirRoute
  '/tv/top-rated': typeof TvTopRatedRoute
  '/movie/': typeof MovieIndexRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie/$id': typeof MovieIdRoute
  '/movie/now-playing': typeof MovieNowPlayingRoute
  '/movie/top-rated': typeof MovieTopRatedRoute
  '/movie/upcoming': typeof MovieUpcomingRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/airing-today': typeof TvAiringTodayRoute
  '/tv/on-the-air': typeof TvOnTheAirRoute
  '/tv/top-rated': typeof TvTopRatedRoute
  '/movie': typeof MovieIndexRoute
  '/tv': typeof TvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie': typeof MovieRouteWithChildren
  '/movie/$id': typeof MovieIdRoute
  '/movie/now-playing': typeof MovieNowPlayingRoute
  '/movie/top-rated': typeof MovieTopRatedRoute
  '/movie/upcoming': typeof MovieUpcomingRoute
  '/tv/$id': typeof TvIdRoute
  '/tv/airing-today': typeof TvAiringTodayRoute
  '/tv/on-the-air': typeof TvOnTheAirRoute
  '/tv/top-rated': typeof TvTopRatedRoute
  '/movie/': typeof MovieIndexRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movie'
    | '/movie/$id'
    | '/movie/now-playing'
    | '/movie/top-rated'
    | '/movie/upcoming'
    | '/tv/$id'
    | '/tv/airing-today'
    | '/tv/on-the-air'
    | '/tv/top-rated'
    | '/movie/'
    | '/tv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movie/$id'
    | '/movie/now-playing'
    | '/movie/top-rated'
    | '/movie/upcoming'
    | '/tv/$id'
    | '/tv/airing-today'
    | '/tv/on-the-air'
    | '/tv/top-rated'
    | '/movie'
    | '/tv'
  id:
    | '__root__'
    | '/'
    | '/movie'
    | '/movie/$id'
    | '/movie/now-playing'
    | '/movie/top-rated'
    | '/movie/upcoming'
    | '/tv/$id'
    | '/tv/airing-today'
    | '/tv/on-the-air'
    | '/tv/top-rated'
    | '/movie/'
    | '/tv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieRoute: typeof MovieRouteWithChildren
  TvIdRoute: typeof TvIdRoute
  TvAiringTodayRoute: typeof TvAiringTodayRoute
  TvOnTheAirRoute: typeof TvOnTheAirRoute
  TvTopRatedRoute: typeof TvTopRatedRoute
  TvIndexRoute: typeof TvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/movie': {
      id: '/movie'
      path: '/movie'
      fullPath: '/movie'
      preLoaderRoute: typeof MovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/': {
      id: '/movie/'
      path: '/'
      fullPath: '/movie/'
      preLoaderRoute: typeof MovieIndexRouteImport
      parentRoute: typeof MovieRoute
    }
    '/tv/top-rated': {
      id: '/tv/top-rated'
      path: '/tv/top-rated'
      fullPath: '/tv/top-rated'
      preLoaderRoute: typeof TvTopRatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/on-the-air': {
      id: '/tv/on-the-air'
      path: '/tv/on-the-air'
      fullPath: '/tv/on-the-air'
      preLoaderRoute: typeof TvOnTheAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/airing-today': {
      id: '/tv/airing-today'
      path: '/tv/airing-today'
      fullPath: '/tv/airing-today'
      preLoaderRoute: typeof TvAiringTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id': {
      id: '/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof TvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/upcoming': {
      id: '/movie/upcoming'
      path: '/upcoming'
      fullPath: '/movie/upcoming'
      preLoaderRoute: typeof MovieUpcomingRouteImport
      parentRoute: typeof MovieRoute
    }
    '/movie/top-rated': {
      id: '/movie/top-rated'
      path: '/top-rated'
      fullPath: '/movie/top-rated'
      preLoaderRoute: typeof MovieTopRatedRouteImport
      parentRoute: typeof MovieRoute
    }
    '/movie/now-playing': {
      id: '/movie/now-playing'
      path: '/now-playing'
      fullPath: '/movie/now-playing'
      preLoaderRoute: typeof MovieNowPlayingRouteImport
      parentRoute: typeof MovieRoute
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof MovieRoute
    }
  }
}

interface MovieRouteChildren {
  MovieIdRoute: typeof MovieIdRoute
  MovieNowPlayingRoute: typeof MovieNowPlayingRoute
  MovieTopRatedRoute: typeof MovieTopRatedRoute
  MovieUpcomingRoute: typeof MovieUpcomingRoute
  MovieIndexRoute: typeof MovieIndexRoute
}

const MovieRouteChildren: MovieRouteChildren = {
  MovieIdRoute: MovieIdRoute,
  MovieNowPlayingRoute: MovieNowPlayingRoute,
  MovieTopRatedRoute: MovieTopRatedRoute,
  MovieUpcomingRoute: MovieUpcomingRoute,
  MovieIndexRoute: MovieIndexRoute,
}

const MovieRouteWithChildren = MovieRoute._addFileChildren(MovieRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieRoute: MovieRouteWithChildren,
  TvIdRoute: TvIdRoute,
  TvAiringTodayRoute: TvAiringTodayRoute,
  TvOnTheAirRoute: TvOnTheAirRoute,
  TvTopRatedRoute: TvTopRatedRoute,
  TvIndexRoute: TvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
